general.live_config_reload = true
general.import = ["themes/zenbones_dark.toml"]

[font]
size = 16.0
normal = { family = "IosevkaTerm NFM", style = "Regular" }
bold = { family = "IosevkaTerm NFM SemiBold", style = "SemiBold" }
italic = { family = "IosevkaTerm NFM Light", style = "Light" }
bold_italic = { family = "IosevkaTerm NFM SemiBold", style = "SemiBold" }

[cursor]
style = { shape = "Block", blinking = "Never" }

[window]
option_as_alt = "Both"
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 10, y = 0 }

[env]
TERM = "xterm-256color"
