live_config_reload = true
# tabspaces = 2

[colors]
# draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#181818"
foreground = "#cecece"

[colors.cursor]
text = "#181818"
cursor = "#cd974b"

[colors.selection]
background = "#293334" 
text = "#cecece"

[colors.normal]
black = "#000000"
red = "#d2322d"
green = "#6abf40"
yellow = "#cd974b"
blue = "#2384C4"
magenta = "#9B3596"
cyan = "#178F79"
white = "#cecece"

[colors.bright]
black = "#333333"
red = "#c33c33"
green = "#95cb82"
yellow = "#dfdf8e"
blue = "#71aed7"
magenta = "#cc8bc9"
cyan = "#47BEA9"
white = "#ffffff"

# [colors.hints.end]
# background = "#1f1d2e"
# foreground = "#6e6a86"
#
# [colors.hints.start]
# background = "#1f1d2e"
# foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/opt/homebrew/bin/fish"

# [visual_bell]
# animation = "EaseOutExpo"
# duration = 0

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 10
