general.live_config_reload = true
general.import = ["themes/zenbones_dark.toml"]

[font]
size = 16.0
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "SemiBold" }
italic = { family = "Iosevka Nerd Font", style = "Light" }
bold_italic = { family = "Iosevka Nerd Font", style = "SemiBold" }

[cursor]
style = { shape = "Block", blinking = "Never" }

[window]
option_as_alt = "Both"
decorations = "Buttonless"
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[env]
TERM = "xterm-256color"
