include themes/rose-pine.conf

# FONTS
font_size 15.0
font_family      Fira Code
bold_font        Fira Code SemiBold
italic_font      Fira Code Light
bold_italic_font Fira Code SemiBold
adjust_column_width -1

# CURSOR
cursor_shape block
shell_integration enabled no-cursor

# BACKGROUND
background_opacity 0.95
background_blur 40

# ENVIRONMENT
env TERM = "xterm-256color"

# MACOS
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
map ctrl+cmd+f toggle_fullscreen 
hide_window_decorations titlebar-only

# TAB BAR
tab_bar_edge top

# WINDOW
remember_window_size  no
initial_window_width  720
initial_window_height 469
# top, horizontal, bottom
# window_padding_width 20 5 5
window_padding_width 5

