[colors.primary]
foreground = "#B4BDC3"
background = "#121212"

[colors.selection]
text = "#B4BDC3"
background = "#3D4042"

[colors.cursor]
cursor = "#C4CACF"
text = "#181818"

[colors.normal]
black   = "#181818"
red     = "#DE6E7C"
green   = "#819B69"
yellow  = "#B77E64"
blue    = "#6099C0"
magenta = "#B279A7"
cyan    = "#66A5AD"
white   = "#B4BDC3"

[colors.bright]
black   = "#403833"
red     = "#E8838F"
green   = "#8BAE68"
yellow  = "#D68C67"
blue    = "#61ABDA"
magenta = "#CF86C1"
cyan    = "#65B8C1"
white   = "#888F94"
