require('base')
require('highlights')
require('maps')
require('plugin-setup')
require('commands')
require('autocmds')
require('statusline')
-- require('toggle-terminal')
require('lsp')
require('color-preview')

-- Highlights linking (Needs to be here before initial draw)
vim.api.nvim_set_hl(0, "NormalFloat", { link = "Normal" })
